# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Fetch csv file and generate json file 
      run: |
          git clone https://github.com/omarudolley/csv-to-json
          cd csv-to-json
          poetry install 
          poetry add  gdown
          poetry run gdown https://drive.google.com/uc?id=1LAgLzi0GwDAZSNP-XSfi7Xhurr204ocM
          poetry run python main.py database.csv --output-dir data --output-file-name schools.json
    - name: Install nextjs dependencies and build applications   
      run: |
            pnpm install
            pnpm run build --if-present
            pnpm next export
    - name: Clean up task 
      run: |
            rm -f database.csv
            rm -rf data
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: out # The folder the action should deploy.
